<?php


class Main extends CI_Controller
{

	public function index()
	{

		$this->load->view('main_view');
	}

	public function form_validation()
	{
		//echo 'ok';

		$this->load->library('form_validation');
		$this->form_validation->set_rules("username","User Name",'required|alpha');
		$this->form_validation->set_rules("email","E-mail",'required');



		if($this->form_validation->run())
		{

			// kickbox for mail verification
			// This file is generated by Composer
			require_once 'C:\wamp64\www\CodeIgniter\application\vendor\autoload.php';

			$client   = new Kickbox\Client('live_986b7c0e3c0adb2f02f78979e2b38d91fb008dff6248b90415c3a3b4b2699a9e');
			$kickbox  = $client->kickbox();

			$response = null;
			try {
				$response = $kickbox->verify($this->input->post("email"));
				//var_dump($response);
			}
			catch (Exception $e) {
				echo "Code: " . $e->getCode() . " Message: " . $e->getMessage();
			}
			//$response1 = json_decode($response);
			$response1 = $response->body['reason'];




			// check if google Recaptcha wokrs
			$secretKey = "6LdqcccUAAAAABiL37Tq-DZzrEtdKC5_z4PfaJj0";
			$responseKey = $_POST['g-recaptcha-response'];
			$userIP = $_SERVER['REMOTE_ADDR'];
			$url = "https://www.google.com/recaptcha/api/siteverify?secret=$secretKey&response=$responseKey&remoteip=$userIP";
			$recaptcha_respone = file_get_contents($url);
			$recaptcha_respone = json_decode($recaptcha_respone);

			if($recaptcha_respone->success && $response1=='accepted_email')
			{
			$data = array(
				"username" =>$this->input->post("username"),
				"email" =>$this->input->post("email")
			);
			$this->load->model("user_model","mm");
			$this->mm->insert_data($data);


			redirect(base_url() . "main/details");
			}
			else{
				?>
				<script>
				/*	$('register').on('click',function (e) {
						e.preventDefault();
						// notif dialog
						bs4pop.notice('Notifications message',{
							type: 'primary',
							position: 'topright',
							appendType: 'append',
							closeBtn: true,
							className: ''
						})
					})*/
				alert('verification failed')
				</script>
				<?php
				$this->index();

			}
		}
		else{
			$this->index();

		}
	}

		public function details()
	{
		$this->load->model("user_model","mm");
		$data["data_details"]= $this->mm->getDetails();
		$this->load->view("details_view",$data);
	}

}
/*$recaptcha_url = 'https://www.google.com/recaptcha/api/siteverify';
							$recaptcha_secret = '6LfLbccUAAAAAGCt9yT9WzvOsTBKcJw431VEIoPM';
							$recaptcha_response = $_POST['recaptcha_response'];
							// Make and decode POST request:
							$recaptcha = file_get_contents($recaptcha_url . '?secret=' . $recaptcha_secret . '&response=' . $recaptcha_response);
							$recaptcha = json_decode($recaptcha);*/



// validation of the email address deg
/*$public_key =  public_WXA5VGtUTXAvY2FoSVhjaWpzZEtWdz09;
$email_to_verify =
$curl = curl_init();

curl_setopt_array($curl, array(
    CURLOPT_URL => "https://api.debounce.io/v1/?api=$public_key&email=&photo=",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_SSL_VERIFYHOST => 0,
    CURLOPT_SSL_VERIFYPEER => 0,
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
    echo "cURL Error #:" . $err;
} else {
    echo $response;
}*/
